# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f05356c4bb06b55f2f98e787b5209ca729838f6eedf40694022cf8490aeca40998566457beaa02dd211d003e74e481d781e0c67d8744533d55a9dead827f62b8

test:
  secret_key_base: 60dbdc14a7f3d0425cc92ab6b1a203f31cd727aaa99f92734912addeb2cb2ab68e31458c3eb3db5844a663af963838938ec60b943d15625e6606635a5a2f4b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
